{{- if .Values.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "stable-diffusion.fullname" . }}
  labels:
    {{- include "stable-diffusion.labels" . | nindent 4 }}
spec:
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "stable-diffusion.fullname" . }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 10
            periodSeconds: 60
  triggers:
  - metadata:
      type: Utilization
      value: "{{ .Values.autoscaling.targetCPUUtilizationPercentage }}"
    type: cpu
{{- end }}