---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-env-configmap
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  {{- with .Values.environmentVariables }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
