apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glance.fullname" . }}-env-configmap
  labels:
    {{- include "glance.labels" . | nindent 4 }}
data:
  {{- with .Values.environmentVariables }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glance.fullname" . }}-etc-configmap
  labels: 
    {{- include "glance.labels" . | nindent 4 }}
data:
  glance.yml: |
    {{ .Values.config | nindent 4 }}