---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "flux-suspensions-exporter.fullname" . }}-role
rules:
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    verbs: ["get", "list"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "flux-suspensions-exporter.fullname" . }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "flux-suspensions-exporter.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "flux-suspensions-exporter.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io