---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "katalog-agent.fullname" . }}-role
rules:
  - apiGroups: ["", "apps"]
    resources: ["namespaces", "deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "katalog-agent.fullname" . }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "katalog-agent.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "katalog-agent.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io