apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "katalog-agent.fullname" . }}-env-configmap
  labels:
    {{- include "katalog-agent.labels" . | nindent 4 }}
data:
  {{- with .Values.environmentVariables }}
  {{- toYaml . | nindent 2 }}
  {{- end }}