{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.persistence.pvc.name }}
spec:
    accessModes:
        - {{ .Values.persistence.pvc.accessMode | default "ReadWriteMany" }}
    storageClassName: {{ .Values.persistence.pvc.storageClassName }}
    resources:
        requests:
            storage: {{ .Values.persistence.pvc.size }}
{{- end }}