apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "migrations.fullname" . }}-env-configmap
  labels:
    {{- include "migrations.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"   
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  {{- with .Values.environmentVariables }}
  {{- toYaml . | nindent 2 }}
  {{- end }}